[project]
name = "my_pgp"
version = "0.1.0"
requires-python = ">=3.14"

[dependency-groups]
dev = [
    "pre-commit==4.6.2",
    "pytest==9.1.1",
    "ruff==0.16.8"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
exclude = [
    ".git",
    ".github",
    ".venv"
]
line-length = 80

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]
