name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - name: Build
      run: make

    - name: Program runs without dependencies
      run: echo "ml" | ./my_pgp xor -c 1234

    - name: Install dev dependencies
      run: make dev

    - name: Coding style
      run: .venv/bin/pre-commit run --all-files --show-diff-on-failure

    - name: Tests
      run: make tests
