name: Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7

    - uses: actions/setup-python@v7
      with:
        python-version: "3.14"

    - name: Build
      run: make

    - name: Program runs without dependencies
      run: ./my_pgp

    - name: Install dev dependencies
      run: make dev

    - name: Lint
      run: .venv/bin/ruff check --output-format github

    - name: Format
      run: .venv/bin/ruff format --check --diff

    - name: Tests
      run: make tests
